workflows:
  android-app:
    name: Android Matriculas App Build
    max_build_duration: 30
    environment:
      xcode: latest
      node: 16.x
    scripts:
      - chmod +x ./gradlew
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
